#!/usr/bin/env python3
"""Create a reproducible FAIR-LENS pathway-coding validation sample.

Run from the repository root (Python 3.9+, standard library only):

    python scripts/sample_validation_assignments.py

Inputs:
    outputs/tri_results_Q1.csv
    ...
    outputs/tri_results_Q6.csv

The unit of sampling is a positively coded paper--pathway assignment.
Twenty assignments are sampled independently from each of the six pathways.

The script creates the sampling records and reviewer templates. Human
validation decisions are entered manually and are not generated by this script.
"""

import argparse
import csv
import hashlib
import io
import json
import platform
import random
import re
import subprocess
import unicodedata
from datetime import datetime, timezone
from pathlib import Path


VERSION = "1.1.0"

# Fixed seed used to make the sampling reproducible.
DEFAULT_SEED = 20261001

PATHWAYS = {
    "Q1": (
        "RP1",
        "Explanation Requirements",
        "Fairness -> Explainability",
        (
            "Fairness or bias concerns motivate, shape, or define explanation "
            "requirements for transparency, contestability, recourse, and "
            "accountability."
        ),
    ),
    "Q2": (
        "RP2",
        "Fairness Evidence",
        "Explainability -> Fairness",
        (
            "XAI or explanation methods are used to examine fairness problems, "
            "including bias, unfairness, proxy effects, identity cues, or "
            "uneven outcomes."
        ),
    ),
    "Q3": (
        "RP3",
        "Fairness Specification",
        "Fairness -> LLMs",
        (
            "Fairness or bias principles define, adapt, or operationalize "
            "criteria for LLM evaluation, benchmark construction, design, "
            "alignment, monitoring, or deployment."
        ),
    ),
    "Q4": (
        "RP4",
        "Fairness Impacts",
        "LLMs -> Fairness",
        (
            "LLM behavior or outputs are assessed as evidence of fairness-related "
            "outcomes, including bias, refusals, omissions, toxicity, harms, "
            "or unequal quality of service."
        ),
    ),
    "Q5": (
        "RP5",
        "Model Behavior",
        "Explainability -> LLMs",
        (
            "XAI or interpretability methods are applied to inspect LLM behavior, "
            "including prompts, outputs, tokens, retrieved context, "
            "representations, activations, or internal mechanisms."
        ),
    ),
    "Q6": (
        "RP6",
        "Explanation Mediation",
        "LLMs -> Explainability",
        (
            "LLMs support explanation practices by generating, translating, "
            "summarizing, evaluating, mediating, or producing natural-language "
            "explanations and rationales."
        ),
    ),
}

META = ["title", "year", "venue", "url", "abstract"]
MISSING = {"", "nan", "none", "null", "n/a", "<na>"}


def clean(value):
    value = str(value or "").strip()
    return "" if value.casefold() in MISSING else value


def normalized_title(title):
    return " ".join(
        unicodedata.normalize("NFKC", title).casefold().split()
    )


def paper_key(row):
    """Create a stable paper identity from normalized title and year."""
    title = normalized_title(clean(row.get("title")))

    if not title:
        raise ValueError(
            "A record has no title; resolve its identity before sampling."
        )

    year = clean(row.get("year"))

    if year and not re.fullmatch(r"\d{4}(?:\.0+)?", year):
        raise ValueError("Invalid publication year: " + repr(year))

    year = year.split(".")[0]

    return json.dumps(
        [title, year],
        ensure_ascii=False,
        separators=(",", ":"),
    )


def paper_id(key):
    return "P-" + hashlib.sha256(
        key.encode("utf-8")
    ).hexdigest()[:20]


def load_pools(input_dir):
    """Load the complete positive-assignment sampling frame."""

    pools = {}
    provenance = []
    papers = {}
    warnings = []
    ids = {}

    for qid in PATHWAYS:
        source = Path(input_dir) / f"tri_results_{qid}.csv"
        raw = source.read_bytes()

        if raw.startswith(
            b"version https://git-lfs.github.com/spec/"
        ):
            raise ValueError(
                f"{source} is a Git LFS pointer, not a CSV."
            )

        reader = csv.DictReader(
            io.StringIO(
                raw.decode("utf-8-sig"),
                newline="",
            )
        )

        required = {
            "question_id",
            "relevant",
            "title",
            "year",
        }

        if not required.issubset(reader.fieldnames or []):
            raise ValueError(
                f"{source} lacks required columns: "
                f"{sorted(required)}"
            )

        pool = {}

        for record_number, row in enumerate(reader, 1):

            if None in row or any(
                row.get(k) is None for k in required
            ):
                raise ValueError(
                    f"Malformed CSV record "
                    f"{record_number} in {source}"
                )

            if clean(row["question_id"]) != qid:
                raise ValueError(
                    f"Unexpected question_id in "
                    f"{source}, record {record_number}"
                )

            if clean(row["relevant"]).casefold() not in {
                "true",
                "1",
                "yes",
            }:
                raise ValueError(
                    f"{source} must contain positive "
                    f"assignments only; record "
                    f"{record_number} does not."
                )

            key = paper_key(row)

            if key in pool:
                raise ValueError(
                    "Duplicate paper-pathway assignment "
                    f"in {source}: {row['title']}. "
                    "Resolve before sampling."
                )

            pid = paper_id(key)

            if pid in ids and ids[pid] != key:
                raise ValueError(
                    "Paper identifier collision; "
                    "increase identifier length."
                )

            ids[pid] = key

            item = {
                field: clean(row.get(field))
                for field in META
            }

            item["year"] = item["year"].split(".")[0]

            item.update(
                paper_id=pid,
                paper_key=key,
                question_id=qid,
                source_file=source.name,
                source_record=record_number,
                model_reason=clean(row.get("reason")),
                model_claim=clean(
                    row.get("directional_claim")
                ),
            )

            pool[key] = item

            if key not in papers:
                papers[key] = {
                    k: item[k]
                    for k in ["paper_id"] + META
                }

            else:
                for field in [
                    "venue",
                    "url",
                    "abstract",
                ]:
                    old = papers[key][field]
                    new = item[field]

                    if (
                        old
                        and new
                        and " ".join(old.split())
                        != " ".join(new.split())
                    ):
                        warnings.append(
                            f"Metadata differs across "
                            f"exports for {pid}: {field}. "
                            "Check sources; no record excluded."
                        )

                    elif not old and new:
                        papers[key][field] = new

        pools[qid] = pool

        provenance.append(
            {
                "file": source.name,
                "bytes": len(raw),
                "sha256": hashlib.sha256(
                    raw
                ).hexdigest(),
                "positive_assignments": len(pool),
            }
        )

    return (
        pools,
        papers,
        provenance,
        sorted(set(warnings)),
    )


def pathway_seed(seed, qid):
    """
    Derive a separate deterministic seed for each pathway.

    The namespace string is retained so that the selection remains
    identical to the previously generated sample.
    """
    text = (
        f"FAIR-LENS-positive-audit-v1|"
        f"{seed}|{qid}"
    )

    return int(
        hashlib.sha256(
            text.encode("utf-8")
        ).hexdigest(),
        16,
    )


def select_assignments(
    pools,
    per_pathway,
    seed,
):
    """
    Randomly sample assignments without replacement
    independently within each pathway.
    """

    if per_pathway < 1:
        raise ValueError(
            "--per-pathway must be at least 1."
        )

    selected = {}

    for qid in PATHWAYS:
        # Sorting means that sampling does not depend on
        # the original CSV row order.
        keys = sorted(pools[qid])

        if len(keys) < per_pathway:
            raise ValueError(
                f"{qid} has {len(keys)} assignments; "
                f"cannot select {per_pathway} "
                "without replacement."
            )

        rng = random.Random(
            pathway_seed(seed, qid)
        )

        selected[qid] = sorted(
            rng.sample(keys, per_pathway)
        )

    return selected


def write_csv(path, fields, rows):
    with Path(path).open(
        "w",
        encoding="utf-8-sig",
        newline="",
    ) as stream:

        writer = csv.DictWriter(
            stream,
            fieldnames=fields,
            extrasaction="ignore",
            lineterminator="\n",
        )

        writer.writeheader()
        writer.writerows(rows)


def local_git_commit(input_dir):
    try:
        result = subprocess.run(
            [
                "git",
                "-C",
                str(Path(input_dir).resolve()),
                "rev-parse",
                "HEAD",
            ],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )

        return result.stdout.strip()

    except (OSError, subprocess.SubprocessError):
        return None


def export_sample(
    input_dir,
    outdir,
    per_pathway=20,
    seed=DEFAULT_SEED,
    source_ref=None,
):

    outdir = Path(outdir)

    if outdir.exists():
        raise ValueError(
            f"Output directory already exists: "
            f"{outdir}. Remove/rename it or specify "
            "a different --outdir."
        )

    (
        pools,
        papers,
        sources,
        warnings,
    ) = load_pools(input_dir)

    selected = select_assignments(
        pools,
        per_pathway,
        seed,
    )

    chosen = sorted(
        set().union(
            *(
                set(keys)
                for keys in selected.values()
            )
        )
    )

    membership = {
        (qid, key)
        for qid, keys in selected.items()
        for key in keys
    }

    sample_rows = []
    frame_rows = []
    strata = []

    # -------------------------------------------------
    # Construct sampling frame and selected assignments
    # -------------------------------------------------

    for qid, pool in pools.items():

        (
            rp,
            name,
            direction,
            _definition,
        ) = PATHWAYS[qid]

        size = len(pool)

        strata.append(
            {
                "question_id": qid,
                "pathway": rp,
                "name": name,
                "population_assignments": size,
                "sample_assignments": per_pathway,
                "inclusion_probability":
                    per_pathway / size,
                "assignment_weight":
                    size / per_pathway,
            }
        )

        for key in sorted(pool):

            row = dict(
                pool[key],
                pathway=rp,
                pathway_name=name,
                direction=direction,
                assignment_id=(
                    pool[key]["paper_id"]
                    + "-"
                    + qid
                ),
                selected=int(
                    (qid, key) in membership
                ),
                inclusion_probability=(
                    per_pathway / size
                ),
                assignment_weight=(
                    size / per_pathway
                ),
            )

            frame_rows.append(row)

            if (qid, key) in membership:
                sample_rows.append(row)

    # -------------------------------------------------
    # Unique paper list
    # -------------------------------------------------

    paper_rows = [
        dict(papers[key])
        for key in chosen
    ]

    # -------------------------------------------------
    # Reviewer rows
    #
    # IMPORTANT:
    # Each reviewer receives ONLY the 120 sampled
    # paper--pathway assignments.
    #
    # A paper that was sampled in two pathways therefore
    # appears twice, because the unit of validation is the
    # paper--pathway assignment.
    #
    # The model justification is retained because the
    # manuscript states that it was considered during the
    # validation check.
    # -------------------------------------------------

    reviewer_rows = []

    for row in sample_rows:

        reviewer_rows.append(
            {
                "assignment_id":
                    row["assignment_id"],
                "paper_id":
                    row["paper_id"],
                "title":
                    row["title"],
                "year":
                    row["year"],
                "venue":
                    row["venue"],
                "url":
                    row["url"],
                "abstract":
                    row["abstract"],
                "question_id":
                    row["question_id"],
                "pathway":
                    row["pathway"],
                "pathway_name":
                    row["pathway_name"],
                "direction":
                    row["direction"],
                "model_reason":
                    row["model_reason"],
                "model_claim":
                    row["model_claim"],
                "human_label": "",
                "reading_scope": "",
                "full_text_url": "",
                "evidence_location": "",
                "evidence_excerpt": "",
                "rationale": "",
                "reviewer": "",
                "review_date": "",
            }
        )

    # -------------------------------------------------
    # Create output structure
    # -------------------------------------------------

    coordinator_dir = outdir / "coordinator"
    reviewer_dir = outdir / "reviewers"

    coordinator_dir.mkdir(
        parents=True,
        exist_ok=False,
    )

    reviewer_dir.mkdir()

    # -------------------------------------------------
    # Sampling frame
    # -------------------------------------------------

    frame_fields = [
        "assignment_id",
        "paper_id",
        "question_id",
        "pathway",
        "pathway_name",
        "direction",
        "title",
        "year",
        "venue",
        "url",
        "source_file",
        "source_record",
        "selected",
        "inclusion_probability",
        "assignment_weight",
    ]

    write_csv(
        coordinator_dir / "sampling_frame.csv",
        frame_fields,
        frame_rows,
    )

    # -------------------------------------------------
    # Selected sample
    # -------------------------------------------------

    selected_fields = (
        frame_fields
        + [
            "abstract",
            "model_reason",
            "model_claim",
        ]
    )

    write_csv(
        coordinator_dir
        / "selected_assignments.csv",
        selected_fields,
        sample_rows,
    )

    # -------------------------------------------------
    # Pathway sampling summary
    # -------------------------------------------------

    write_csv(
        coordinator_dir
        / "pathway_summary.csv",
        list(strata[0]),
        strata,
    )

    # -------------------------------------------------
    # Unique papers represented in the sample
    # -------------------------------------------------

    write_csv(
        reviewer_dir / "papers_for_review.csv",
        ["paper_id"] + META,
        paper_rows,
    )

    # -------------------------------------------------
    # Reviewer templates:
    # 120 rows per researcher
    # -------------------------------------------------

    review_fields = [
        "assignment_id",
        "paper_id",
        "title",
        "year",
        "venue",
        "url",
        "abstract",
        "question_id",
        "pathway",
        "pathway_name",
        "direction",
        "model_reason",
        "model_claim",
        "human_label",
        "reading_scope",
        "full_text_url",
        "evidence_location",
        "evidence_excerpt",
        "rationale",
        "reviewer",
        "review_date",
    ]

    for reviewer in (1, 2):
        write_csv(
            reviewer_dir
            / f"reviewer_{reviewer}.csv",
            review_fields,
            reviewer_rows,
        )

    # -------------------------------------------------
    # Adjudication template
    # -------------------------------------------------

    adjudication_rows = []

    for row in sample_rows:

        adjudication_rows.append(
            {
                "assignment_id":
                    row["assignment_id"],
                "paper_id":
                    row["paper_id"],
                "title":
                    row["title"],
                "question_id":
                    row["question_id"],
                "pathway":
                    row["pathway"],
                "pathway_name":
                    row["pathway_name"],
                "direction":
                    row["direction"],
                "model_reason":
                    row["model_reason"],
                "model_claim":
                    row["model_claim"],
                "reviewer_1_label": "",
                "reviewer_2_label": "",
                "initial_human_disagreement": "",
                "final_label": "",
                "final_differs_from_model": "",
                "resolution_notes": "",
            }
        )

    adjudication_fields = [
        "assignment_id",
        "paper_id",
        "title",
        "question_id",
        "pathway",
        "pathway_name",
        "direction",
        "model_reason",
        "model_claim",
        "reviewer_1_label",
        "reviewer_2_label",
        "initial_human_disagreement",
        "final_label",
        "final_differs_from_model",
        "resolution_notes",
    ]

    write_csv(
        coordinator_dir / "adjudication.csv",
        adjudication_fields,
        adjudication_rows,
    )

    # -------------------------------------------------
    # Pathway definitions
    # -------------------------------------------------

    codebook = [
        {
            "question_id": qid,
            "pathway": rp,
            "name": name,
            "direction": direction,
            "definition": definition,
        }
        for qid, (
            rp,
            name,
            direction,
            definition,
        ) in PATHWAYS.items()
    ]

    write_csv(
        reviewer_dir
        / "pathway_definitions.csv",
        list(codebook[0]),
        codebook,
    )

    # -------------------------------------------------
    # Manifest
    # -------------------------------------------------

    report = {
        "script_version":
            VERSION,

        "created_utc":
            datetime.now(
                timezone.utc
            ).isoformat(),

        "purpose":
            (
                "Reproducible sampling and documentation "
                "of the FAIR-LENS pathway-coding "
                "validation sample."
            ),

        "design":
            (
                "Equal-allocation stratified simple random "
                "sampling without replacement of positive "
                "paper-pathway assignments."
            ),

        "sampling_unit":
            "paper-pathway assignment",

        "stratification_variable":
            "question_id",

        "seed":
            seed,

        "per_pathway":
            per_pathway,

        "rng":
            (
                "Python random.Random (MT19937), sample() "
                "over sorted normalized title-year keys"
            ),

        # Retained to reproduce the exact previously
        # generated selection.
        "stratum_seed_derivation":
            (
                "SHA256("
                "FAIR-LENS-positive-audit-v1|"
                "<seed>|<question_id>"
                "), interpreted as an integer"
            ),

        "python_version":
            platform.python_version(),

        "python_implementation":
            platform.python_implementation(),

        "script_sha256":
            hashlib.sha256(
                Path(__file__).read_bytes()
            ).hexdigest(),

        "source_ref_supplied":
            source_ref,

        "local_git_commit":
            local_git_commit(input_dir),

        "input_directory":
            Path(input_dir).as_posix(),

        "input_files":
            sources,

        "paper_identity":
            (
                "NFKC-normalized, casefolded, "
                "whitespace-collapsed title plus "
                "normalized year; inherits upstream "
                "bibliographic deduplication."
            ),

        "population_assignments":
            len(frame_rows),

        "population_unique_papers":
            len(papers),

        "selected_assignments":
            len(sample_rows),

        "selected_unique_papers":
            len(chosen),

        "review_sheet_rows_per_reviewer":
            len(reviewer_rows),

        "missing_abstracts_in_selected_papers":
            sum(
                not p["abstract"]
                for p in paper_rows
            ),

        "missing_urls_in_selected_papers":
            sum(
                not p["url"]
                for p in paper_rows
            ),

        "pathways":
            strata,

        "selected_assignment_ids":
            [
                row["assignment_id"]
                for row in sample_rows
            ],

        "selected_paper_ids":
            [
                papers[key]["paper_id"]
                for key in chosen
            ],

        "warnings":
            warnings,
    }

    # -------------------------------------------------
    # README
    # -------------------------------------------------

    instructions = f"""# FAIR-LENS pathway-coding validation sample

This directory documents the reproducible sampling procedure used for the
manual validation of FAIR-LENS paper--pathway assignments.

## Sample

- Sampling unit: paper--pathway assignment.
- Pathways are used as the six sampling strata.
- {per_pathway} positive assignments are sampled without replacement from each pathway.
- Total sampled assignments: {len(sample_rows)}.
- Unique papers represented: {len(chosen)}.
- Complete positive-assignment frame: {len(frame_rows)} assignments from {len(papers)} unique papers.
- Fixed random seed: {seed}.

Because FAIR-LENS uses multi-label coding, the same paper can legitimately be
sampled under more than one pathway. The {len(sample_rows)} validation cases
therefore correspond to {len(chosen)} unique papers.

## Reviewer files

Each researcher receives reviewer_1.csv or reviewer_2.csv containing the same
{len(sample_rows)} sampled paper--pathway assignments.

For every sampled assignment, the sheet contains:

- paper metadata;
- title and abstract;
- the pathway being checked;
- the model-generated justification and directional claim; and
- blank fields for the researcher's assessment and supporting evidence.

The reviewer records whether the sampled pathway assignment is supported,
unsupported, unclear, or unavailable. The reviewer can consult the full text
where the title and abstract are insufficient and can record the relevant
section/page and evidence.

The same paper may appear more than once when it was independently sampled
under more than one pathway. It need not be read from the beginning again, but
each sampled paper--pathway relation is evaluated separately.

## Comparison of judgments

The two researchers' initial judgments should be retained separately.
coordinator/adjudication.csv can then be used to document:

1. whether the researchers initially differed;
2. the final judgment after discussion; and
3. whether that final judgment differs from the original model assignment.

These quantities should not be conflated.

## Reproducibility

coordinator/sampling_frame.csv contains the complete positive-assignment
sampling frame.

coordinator/selected_assignments.csv contains the {len(sample_rows)} sampled
assignments.

coordinator/pathway_summary.csv records pathway-specific population sizes,
sampling fractions, and weights.

manifest.json records the seed, input hashes, sampled identifiers, and other
provenance information.

The script generates the sample and review templates only. Human validation
judgments are entered manually.
"""

    (outdir / "README.md").write_text(
        instructions,
        encoding="utf-8",
    )

    # -------------------------------------------------
    # Minimal manuscript-ready sampling description
    # -------------------------------------------------

    latex = (
        "\\\\textcolor{red}{Within each of the six "
        "FAIR\\\\textendash LENS pathways, "
        f"{per_pathway} positively coded "
        "paper--pathway assignments were randomly "
        "sampled without replacement, yielding "
        f"{len(sample_rows)} assignments corresponding "
        f"to {len(chosen)} unique papers. Sampling "
        "separately within each pathway ensured that "
        "all six pathways were represented equally "
        "in the validation.}\\n"
    )

    (outdir / "sampling_method.tex").write_text(
        latex,
        encoding="utf-8",
    )

    # -------------------------------------------------
    # Hash generated output files
    # -------------------------------------------------

    report["output_sha256_at_generation"] = {
        str(p.relative_to(outdir)):
            hashlib.sha256(
                p.read_bytes()
            ).hexdigest()
        for p in sorted(
            outdir.rglob("*")
        )
        if p.is_file()
    }

    (outdir / "manifest.json").write_text(
        json.dumps(
            report,
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )

    return report


def main():

    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=(
            argparse.RawDescriptionHelpFormatter
        ),
    )

    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("outputs"),
    )

    parser.add_argument(
        "--outdir",
        type=Path,
        help=(
            "Must not already exist; default: "
            "outputs/validation_sample_seed<seed>"
        ),
    )

    parser.add_argument(
        "--per-pathway",
        type=int,
        default=20,
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
    )

    parser.add_argument(
        "--source-ref",
        help=(
            "Optional source commit/tag for provenance; "
            "input-file hashes remain authoritative."
        ),
    )

    args = parser.parse_args()

    outdir = (
        args.outdir
        or Path("outputs")
        / f"validation_sample_seed{args.seed}"
    )

    try:
        result = export_sample(
            args.input_dir,
            outdir,
            args.per_pathway,
            args.seed,
            args.source_ref,
        )

    except (
        OSError,
        ValueError,
        csv.Error,
    ) as exc:

        parser.exit(
            2,
            f"ERROR: {exc}\n",
        )

    print(
        "Selected "
        f"{result['selected_assignments']} "
        "paper-pathway assignments from "
        f"{result['selected_unique_papers']} "
        "unique papers."
    )

    for row in result["pathways"]:
        print(
            f"  {row['pathway']}: "
            f"{row['sample_assignments']}/"
            f"{row['population_assignments']} "
            "positive assignments"
        )

    print(
        f"Seed: {args.seed}. "
        f"Outputs: {outdir.resolve()}"
    )

    print(
        "Each reviewer sheet contains "
        f"{result['review_sheet_rows_per_reviewer']} "
        "sampled assignments."
    )

    if result["warnings"]:
        print(
            "Metadata warnings: "
            f"{len(result['warnings'])}; "
            "inspect manifest.json."
        )


if __name__ == "__main__":
    main()